- constants/user.py
- tests/test_communities.py
> Fix test on inviting to community for Mac

- driver/aut.py
- tests/test_onboarding.py
> Restart application added

- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/test_wallet/test_wallet_settings.py
https://ethstatus.testrail.net/index.php?/cases/view/703416
> test(Wallet) Settings - account reordering not possible with 1 account

- constants/user.py
- gui/components/change_password_popup.py
- gui/components/profile_popup.py
- gui/main_window.py
- gui/objects_map/component_names.py
- gui/objects_map/main_names.py
- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/test_settings.py
https://ethstatus.testrail.net/index.php?/cases/view/703002 
https://ethstatus.testrail.net/index.php?/cases/view/703003 (joined with 703002 in test)
https://ethstatus.testrail.net/index.php?/cases/view/703004
https://ethstatus.testrail.net/index.php?/cases/view/703005
https://ethstatus.testrail.net/index.php?/cases/view/703006
> Profile settings - display name, states, change password

- constants/wallet.py
- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/test_wallet/test_wallet_settings.py
- Added back button field to NetworkWalletSettings class
- Added subtitle field to NetworkWalletSettings class 
- Added step to verify the testnet subtitle
> chore(@wallet_settings): added verifications for back button and subtitle

- gui/components/onboarding/before_started_popup.py
- gui/components/onboarding/beta_consent_popup.py
- gui/main_window.py
- gui/objects_map/component_names.py
- gui/objects_map/onboarding_names.py
- gui/screens/onboarding.py
- gui/screens/wallet.py
- tests/test_onboarding.py
- added several verifications for several onboarding screens
- renamed some classes to reflect the screens
Depends on https://github.com/status-im/status-desktop/pull/12226
> chore(@onborading): added several verifications

- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/test_settings.py
- tests/test_wallet/test_wallet_settings.py
https://ethstatus.testrail.net/index.php?/cases/edit/703598/1
> test(@wallet_settings): add account from wallet settings view

- constants/syncing.py
- gui/components/settings/sync_new_device_popup.py
- gui/objects_map/component_names.py
- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/test_syncing.py
Depends on https://github.com/status-im/status-desktop/pull/12249
> chore(@syncing_test): adding object names

- constants/group_chat.py
- constants/user.py
- gui/components/messaging/edit_group_name_and_image_popup.py
- gui/components/messaging/leave_group_popup.py
- gui/objects_map/component_names.py
- gui/objects_map/messages_names.py
- gui/screens/messages.py
- gui/screens/settings.py
- tests/test_messaging.py
Group chat test case automated
Scenario - https://ethstatus.testrail.net/index.php?/cases/view/703014
> Group chat

- constants/wallet.py
- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/wallet/test_wallet_settings.py
- Added verification for text string for checkbox
- Added verifications for error messages in input fields
- Added verifications for successful messages when connection established
- Fixed the problem with clicking button too fast
> chore(@edit_network): verification  for checkbox text and successful connection messages

- gui/components/social_links_popup.py
- gui/objects_map/component_names.py
- tests/settings/settings_profile/test_settings_profile_change_password.py
- tests/settings/settings_profile/test_settings_profile_edit.py
Fixes https://github.com/status-im/desktop-qa-automation/issues/146
> fix(@setting_profile tests): fix edit profile and change password

- gui/screens/onboarding.py
- tests/onboarding/test_onboarding_import_seed.py
Added second type of selection when importing seed phrase - with Enter
If all good - I can update test case https://ethstatus.testrail.net/index.php?/cases/view/703040
> Added type of selection of words with enter in seed phrase popup

- gui/components/back_up_your_seed_phrase_banner.py
- gui/objects_map/component_names.py
- tests/settings/test_settings_back_up_seed.py
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/474/
> chore(@back_up_seed_test): improve validations

- constants/wallet.py
- gui/components/wallet/wallet_account_popups.py
- gui/objects_map/component_names.py
- gui/objects_map/settings_names.py
- gui/screens/settings_wallet.py
- tests/settings/settings_wallet/test_wallet_settings_edit_status_account.py
https://ethstatus.testrail.net/index.php?/cases/view/704433
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/504/
> test(@wallet_settings): add test for editing status default account from wallet settings

- gui/main_window.py
- tests/settings/settings_wallet/test_wallet_settings_account_order.py
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/553/
> chore(@main_window): add attempts for button click

- ci/Jenkinsfile
Some minor adjustments. We don't want to prune builds so early.
> ci: bump number of builds to keep

- constants/colors.py
- constants/onboarding.py
- gui/objects_map/onboarding_names.py
- gui/screens/onboarding.py
- tests/onboarding/test_password_strength.py
Small test for review. In old framework verifications were based on screenshots, I changed it completely. 
Test case - https://ethstatus.testrail.net/index.php?/cases/view/702989
Test run on CI - https://ci.status.im/job/status-desktop/job/e2e/job/manual/607/
> Test password strength

- gui/components/wallet/wallet_toast_message.py
- gui/screens/settings_wallet.py
- tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py
Now method gets list of all toast messages and checked that there is more than 1 message.
> Fixed get toast messages method

- tests/onboarding/test_onboarding_syncing.py
> test_sync_device_during_onboarding skipped

- tests/communities/test_communities.py
disable community tests for now
> chore: disable community test for a while

- ci/Jenkinsfile
Improvement upon:
* https://github.com/status-im/desktop-qa-automation/pull/214/files
> ci: set short build name and better description

- driver/aut.py
- driver/context.py
- fixtures/aut.py
- fixtures/squish.py
- scripts/utils/local_system.py
- Close and Detach methods are merged
- Saving pid in Aut changed to close after AttachError
- Collect all pid that use port
> chore: Improve AUT methods

- gui/objects_map/settings_names.py
- gui/screens/settings.py
- tests/settings/test_sign_out_and_quit.py
> test: test_sign_out_and_quit added

- tests/wallet_main_screen/test_wallet_main_saved_addresses.py
Just a small adjustment
https://ci.status.im/job/status-desktop/job/e2e/job/manual/698/
> chore: saved_address test improved

- gui/components/wallet/popup_delete_account_from_settings.py
Initialise the Account removal popup by its header object
> chore: improve reference for a popup in account deletion test

- driver/aut.py
- gui/elements/window.py
- tests/communities/test_communities.py
Test run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/723/
> chore: fix test_sync_device_during_onboarding

- conftest.py
- driver/aut.py
- scripts/tools/image.py
#271
Test Run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/803/
> chore: Create screenshot of multiple instances on test fail

- ci/Jenkinsfile
Currently the logic is a bit messy and results are not great.
> ci: improve build names and descriptions

- ci/Jenkinsfile
Depends on:
* https://github.com/status-im/status-jenkins-lib/pull/79
> ci: fix filename parsing, add sane fallback

- constants/keycard.py
- gui/components/settings/keycard_popup.py
- gui/mocked_keycard_controller.py
- gui/objects_map/component_names.py
- gui/objects_map/mocked_keycard_controller_names.py
- gui/screens/settings_keycard.py
- tests/settings/settings_keycard/test_check_whats_on_keycard.py
Test case:
https://ethstatus.testrail.net/index.php?/cases/view/703627
Local test run
> test: test_check_whats_on_keycard added

- gui/elements/object.py
- gui/elements/window.py
- gui/screens/settings_wallet.py
getattr method deleted in QObject class
> chore: Revert getattr

- constants/keycard.py
- gui/components/settings/keycard_popup.py
- gui/objects_map/component_names.py
- tests/settings/settings_keycard/test_create_keycard_account_with_new_seed_phrase.py
Added more accounts and checked that these accounts added in wallet section
> chore: test_create_keycard_account_with_new_seed_phrase improved

- configs/system.py
- gui/components/onboarding/beta_consent_popup.py
- gui/main_window.py
- gui/objects_map/component_names.py
- tests/onboarding/test_onboarding_generate_new_keys.py
- tests/onboarding/test_onboarding_import_seed.py
- tests/onboarding/test_onboarding_negative_scenarios.py
- tests/onboarding/test_onboarding_syncing.py
- tests/onboarding/test_password_strength.py
Added object names to modal and its components. No changes in tests
Added condition to check env variable
> chore: add object names to beta consent popup and test mode env variable condition

- ci/Jenkinsfile
I found the root cause of tests hangs. Total time is 21 min now for all enabled tests in master
``` 
QT_LOGGING_DEBUG = 1
QT_DEBUG_PLUGINS = 1
```
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1003/console
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1003/allure/
> chore: update jenkins config

- constants/syncing.py
- gui/components/community/authenticate_popup.py
- gui/components/settings/sync_new_device_popup.py
- gui/objects_map/component_names.py
- gui/screens/settings_syncing.py
- tests/onboarding/test_onboarding_syncing.py
СI run -https://ci.status.im/job/status-desktop/job/e2e/job/manual/1074/allure/#suites/8e392deae3ddbc9e03b45d214f2f6e0a/bfd096b69a81e7dc/
> test: test_cancel_setup_syncing added

- ci/Jenkinsfile
- configs/__init__.py
- configs/_local.ci.py
- driver/objects_access.py
- fixtures/path.py
- gui/components/community/create_community_popups.py
- gui/components/os/open_file_dialogs.py
- gui/elements/button.py
- gui/elements/check_box.py
- gui/elements/list.py
- gui/elements/object.py
- gui/elements/scroll.py
- gui/elements/slider.py
- gui/elements/text_edit.py
- gui/elements/text_label.py
- gui/elements/window.py
- gui/main_window.py
- gui/screens/onboarding.py
- gui/screens/settings_communities.py
- pytest.ini
- scripts/tools/image.py
- scripts/utils/system_path.py
- tests/onboarding/test_onboarding_generate_new_keys.py
Also rename `_logger` to `LOG` to match changes from:
* https://github.com/status-im/desktop-qa-automation/pull/352
> feat(ci): add LOG_LEVEL parameter for Jenkins jobs

- ci/Jenkinsfile
- tests/communities/test_communities.py
- tests/settings/settings_profile/test_settings_profile_change_password.py
- tests/wallet_main_screen/test_plus_button_manage_generated_account_custom_derivation_path.py
1. changed Squish version in Jenkins file
2. disabled whatever looks unstable
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1187/
Allure: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1187/allure
> chore: change Squish version and disable flaky tests

- conftest.py
- fixtures/path.py
- gui/elements/button.py
- gui/elements/check_box.py
- gui/elements/object.py
- gui/elements/scroll.py
- gui/elements/slider.py
- gui/elements/text_edit.py
- gui/elements/window.py
Related to:
* https://github.com/status-im/desktop-qa-automation/pull/352
> chore(all) rename _logger to LOG to match refactor

- configs/squish.py
- constants/user.py
- constants/wallet.py
- driver/__init__.py
- driver/objects_access.py
- gui/components/wallet/send_popup.py
- gui/components/wallet/testnet_mode_popup.py
- gui/elements/object.py
- gui/main_window.py
- gui/objects_map/component_names.py
- gui/objects_map/wallet_names.py
- gui/screens/settings.py
- gui/screens/settings_wallet.py
- gui/screens/wallet.py
- tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py
- tests/wallet_main_screen/test_send.py
Test run on CI: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1194/
Test case: https://ethstatus.testrail.net/index.php?/cases/view/704527
> test: test_wallet_send_0_eth added

- driver/aut.py
This avoids issues on slower systems where `startaut` does not have the port ready when the `squishserver` tries to connect to it, resulting in:
```
Warning: Could not connect to attachable AUT at localhost:61500: Connection refused
```
> feat(aut): wait for AUT comms port to become available

- gui/components/community/community_category_popup.py
- gui/components/delete_popup.py
- gui/objects_map/community_names.py
- gui/objects_map/component_names.py
- gui/screens/community.py
- tests/communities/test_communities.py
- tests/communities/test_communities_categories.py
- tests/communities/test_communities_channels.py
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1197/
Test cases:
https://ethstatus.testrail.net/index.php?/cases/view/703226
https://ethstatus.testrail.net/index.php?/cases/view/703227
> test: tests create and remove community category added

- constants/user.py
- gui/components/wallet/send_popup.py
- gui/objects_map/settings_names.py
- gui/screens/settings.py
- gui/screens/settings_ens_usernames.py
- tests/settings/test_ens_name_purchase.py
Test case: https://ethstatus.testrail.net/index.php?/cases/view/704597
Test run on CI: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1202/
> test: test_ens_name_purchase added

- gui/components/community/create_community_popups.py
- gui/screens/messages.py
- gui/screens/settings_messaging.py
- gui/screens/wallet.py
Better handle the way we raise exceptions
> chore: raise exceptions when needed

- tests/onboarding/test_onboarding_syncing.py
Replaced `is_visible` usage with `waitForObjectExists` so test won't time out
CI runs:
1. single test run https://ci.status.im/job/status-desktop/job/e2e/job/manual/1232/
2. onboarding_syncing selection https://ci.status.im/job/status-desktop/job/e2e/job/manual/1233/
3. critical pack including sync test https://ci.status.im/job/status-desktop/job/e2e/job/manual/1235/
> chore: fix syncing test and move it to critical suite

- ci/Jenkinsfile
> ci: set TEST_SCOPE_FLAG conditionally on JOB_NAME

- gui/objects_map/onboarding_names.py
- tests/onboarding/test_onboarding_generate_new_keys.py
Depends on https://github.com/status-im/status-desktop/pull/13107
Added an object name for the view so it could be initialised properly
> chore: change locator for InsertDetailsView

- gui/screens/messages.py
- tests/communities/test_join_community.py
Fixed according to changes: 
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1243/
> chore: fixes for join community test according to changes in the app

- gui/components/community/community_category_popup.py
- gui/objects_map/community_names.py
- gui/objects_map/component_names.py
- gui/screens/community.py
- tests/communities/test_communities_categories.py
Fixes https://github.com/status-im/desktop-qa-automation/issues/381
Test Edit community category added https://ci.status.im/job/status-desktop/job/e2e/job/manual/1219/
I joined these test cases in 1 test, because it doesn't make sense to split it in automated test
https://ethstatus.testrail.net/index.php?/cases/view/703233
https://ethstatus.testrail.net/index.php?/cases/view/703234
https://ethstatus.testrail.net/index.php?/cases/view/703235
> test: edit_community_category

- gui/screens/community.py
- gui/screens/onboarding.py
- tests/onboarding/test_onboarding_generate_new_keys.py
`test_onboarding_generate_new_keys.py` fails sometimes, i suspect again the verification of `is_visible` = True  as a root cause.
In this PR i simply remove this method and replace `Assertion error` with general exception that should be raised
> chore: attempt to fix navigation

- constants/onboarding.py
- scripts/utils/local_system.py
- tests/communities/test_communities_permissions.py
Error message has been changed in https://github.com/status-im/status-desktop/commit/ff9062a1b059c9b58770fd1e2eec19bc7c9a9078#diff-4ac30c280b7ceca7b505ab0551b9e009295aae3147253c43ae8821e9d6c0ed69R682
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1252/allure/#suites/8c8bad42b349ab7d648f7a8503fdb961/cf1212d766644c25/
> chore: update error message

- gui/components/context_menu.py
- gui/components/wallet/confirmation_popup.py
- gui/objects_map/component_names.py
- gui/objects_map/wallet_names.py
- gui/screens/wallet.py
- tests/wallet_main_screen/test_saved_addresses.py
Fixes https://github.com/status-im/desktop-qa-automation/issues/427
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1256/
Allure: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1256/allure/#suites/cb6d131674370780c1a4b3431f502f42/2fd6929266d1ed51/
> Fix saved addresses tests

- constants/user.py
- gui/screens/community.py
- tests/communities/test_communities_categories.py
Test run on Jenkins: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1260/
Allure report:
> test: test clicking category added

- constants/wallet.py
- gui/screens/settings_wallet.py
- tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py
- Changed URLs
- Fixed a bit code, realised that it didn't work good before (always passed on Mac for example)
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1269/
Local Allure report:
> chore: test edit network fixed

- gui/objects_map/wallet_names.py
- gui/screens/wallet.py
- tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py
- tests/settings/test_settings_sign_out_and_quit.py
- tests/wallet_main_screen/test_saved_addresses.py
1. Fix https://github.com/status-im/desktop-qa-automation/issues/447
2. Replace fake test cases references with real ones
CI run for saved addresses https://ci.status.im/job/status-desktop/job/e2e/job/manual/1275/allure/
> Fix saved addresses tests and change test cases references

- constants/colors.py
- gui/objects_map/community_names.py
- gui/objects_map/messages_names.py
- gui/screens/community_settings.py
- gui/screens/messages.py
- tests/communities/test_communities_pin_and_unpin_messages.py
CI  run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1294/
Allure:
> test: pin and unpin message test added

- gui/objects_map/community_names.py
- tests/communities/test_join_community.py
- tests/messages/test_messaging_group_chat.py
- tests/settings/settings_messaging/test_messaging_settings_accept_request.py
- tests/settings/settings_messaging/test_messaging_settings_identity_verification.py
- tests/settings/settings_messaging/test_messaging_settings_reject_request.py
- Fixed edit community channel test
- Disabled tests with contact requests because of bug
- CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1297/
> chore: fix for edit_community_channel test

- tests/communities/test_communities_channels.py
- tests/communities/test_join_community.py
- tests/messages/test_messaging_group_chat.py
- I disabled one test because of bug
- Also two more tests which need to be fixed but I have not managed to fix it today, will continue work on it tomorrow
> chore: disabled some failed tests

- gui/objects_map/settings_names.py
- gui/screens/settings_profile.py
Fixed according to changes
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1340/
> chore: fixes for edit profile test

- tests/wallet_main_screen/wallet: right click out of account area/test_right_click_manage_watched_address.py
- tests/wallet_main_screen/wallet: saved addresses/test_saved_addresses.py
Fixed some cases ids to match the coverage
> chore: fix some references to test rail

- ci/Jenkinsfile
Result:
Depends on:
- https://github.com/status-im/status-jenkins-lib/pull/83
> ci: add Discord notifiction on failure

- tests/settings/settings_wallet/test_wallet_settings_account_order.py
- tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
- tests/settings/settings_wallet/test_wallet_settings_add_account.py
- tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py
- tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py
small changes to wallet settings tests
> chore: small changes to wallet settings tests

- gui/components/wallet/wallet_account_popups.py
- gui/objects_map/names.py
- gui/screens/messages.py
- gui/screens/onboarding.py
- tests/messages/test_messaging_group_chat.py
- Fixed according to changes for seed phrase
- (hopefully) fixed the issue with group chat - added break in cycle 
CI runs
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1411/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1412/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1413/
> chore: fixes of fails from nightly run (seed phrase + group chat)

- constants/messaging.py
- constants/onboarding.py
- gui/components/settings/verify_identity_popup.py
- tests/communities/test_communities_permissions.py
- Fixed messaging and sign up with wrong name according to changes in product
- Marked xfail permissions test (bug)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1450/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1454/
> chore: fixes for nightly run fails

- ci/Jenkinsfile
- driver/aut.py
- driver/context.py
I recreated https://github.com/status-im/desktop-qa-automation/pull/485 to keep commits clean
Fixes #501 
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1369/allure/#suites/3275d693ce3d6e2e89bf72642e1cabcb/f58a7c59d092b713/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1367/allure/#suites/3275d693ce3d6e2e89bf72642e1cabcb/bfadd33e5f4935e6/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1368/allure/#suites/3275d693ce3d6e2e89bf72642e1cabcb/d0b5bb878aebcfa4/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1426/
> chore: try to fix connection refused error

- ci/Jenkinsfile
- tests/onboarding/test_password_strength.py
Remove     `QT_QPA_PLATFORMTHEME = 'qt5ct'` , we don't need it anymore
> chore: remove QT_QPA_PLATFORMTHEME = 'qt5ct' 

- gui/components/context_menu.py
- gui/screens/community.py
- tests/communities/test_communities_channels.py
It feels like this test was always passing, so kind of false positive
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1503/allure/#suites/a9b9ce4ef70730fb5814a5009e98b445
> chore: fix validations for members role community channel test

- gui/components/change_password_popup.py
- gui/components/changes_detected_popup.py
- tests/communities/test_communities_permissions.py
increase timeout for password test and remove validations for toasts
> chore: increase timeout for password test and remove validations for toasts

- tests/communities/test_communities.py
- tests/onboarding/test_onboarding_generate_new_keys.py
- tests/onboarding/test_password_strength.py
- tests/settings/settings_messaging/test_messaging_settings_accept_request.py
- tests/settings/test_ens_name_purchase.py
comment out password strength test and other minor updates
> chore: comment out password strength test and other minor updates

- gui/screens/community_settings.py
- Added object name for add item buttons, so refactored methods
- Added attempts during new permission creation
Run all tests several times:
- https://ci.status.im/job/status-desktop/job/e2e/job/manual/1557/allure/
- https://ci.status.im/job/status-desktop/job/e2e/job/manual/1562/allure/
> chore: permissions test stabilised

- tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py
change ticket reference and remove xfail mark
> chore: change ticket reference and remove xfail mark

- tests/online_identifier/test_online_identifier.py
- tests/settings/settings_profile/test_settings_profile_edit.py
https://github.com/status-im/status-desktop/issues/13868 is logged
> chore: skip edit tests because of bug

- gui/components/changes_detected_popup.py
- tests/settings/settings_profile/test_settings_profile_edit.py
- fix edit profile test itself and added reference
> chore: improve edit test

- tests/settings/test_ens_name_purchase.py
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1646/
> chore: enable ens name purchase test

- constants/colors.py
- gui/objects_map/communities_names.py
- gui/screens/community.py
- tests/online_identifier/test_online_identifier.py
- Joined 2 tests together
- Refactored it using multiple instances and checking state in community
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1636/
> chore: test switch state to offline, online or automatic updated

- tests/settings/test_ens_name_purchase.py
ENS name purchase test skipped
> chore: disabled test ens_name_purchase because of bug

- tests/communities/test_communities.py
- tests/onboarding/test_onboarding_import_seed.py
- tests/settings/test_ens_name_purchase.py
enable ens test because bug is fixed
bring back import seed test to critical path
bring back edit community test to critical path
> chore: enable tests

- gui/components/activity_center.py
- gui/components/delete_popup.py
- gui/objects_map/communities_names.py
- gui/objects_map/messaging_names.py
- gui/objects_map/names.py
- gui/screens/messages.py
- tests/messages/test_1x1_chat.py
- tests/settings/settings_messaging/test_1x1_chat.py
Test for 1-1 chat created
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1675/allure/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1689/ - after changes for stabilisation
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1691/ - after changes for stabilisation
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1692/ - whole run after changes for stabilisation
> 1-1 chat, send reply, send emoji, edit, delete and cannot delete other member message

- gui/components/community/authenticate_popup.py
- gui/objects_map/names.py
- tests/communities/test_communities_pin_and_unpin_messages.py
- tests/online_identifier/test_online_identifier.py
Changes from here https://www.figma.com/file/qHfFm7C9LwtXpfdbxssCK3/Kuba%E2%8E%9CDesktop---Communities?type=design&node-id=45015-290141&mode=design&t=29lQZt4UsST8Ep27-4
> chore: remove unnecessary step from joining community flow

- gui/elements/object.py
- Removed isFrozen verification from click 
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1690/
> chore: removed isFrozen

- gui/components/wallet/add_saved_address_popup.py
- tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py
- added a bug to address failure in edit network https://github.com/status-im/status-desktop/issues/14228
- attempt to stabilize clicking of checkboxes
https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/view/change-requests/job/PR-619/1/console
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1725/console
> chore: address nightly failures on march 29, 2024

- tests/settings/test_ens_name_purchase.py
Ticket opened: https://github.com/status-im/status-desktop/issues/14262
> chore: disable ens purchase test because of issue

- .gitignore
- constants/community_settings.py
- gui/objects_map/communities_names.py
- gui/screens/community_settings.py
- tests/communities/test_communities_permissions.py
Closing https://github.com/status-im/desktop-qa-automation/issues/602
https://ethstatus.testrail.net/index.php?/cases/view/722918
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1729/allure/#suites/ea35bd66d78deeec4a096260dd1d8144/ea93f096cc712bd6/
> test: check member role permission limit added

- pytest.ini
- tests/communities/test_communities_permissions.py
- tests/settings/test_ens_name_purchase.py
- tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send.py
Closes https://github.com/status-im/desktop-qa-automation/issues/626
1 min 10 seconds against 3.75 minutes
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1761/allure/#suites/ea35bd66d78deeec4a096260dd1d8144/3c4f68af658cd8f5/
> chore: rework permissions test to manipulate with the permissions in one go

- tests/settings/settings_wallet/test_wallet_settings_account_order.py
Closes https://github.com/status-im/desktop-qa-automation/issues/519
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1763/allure/#suites/96c8fa12a723416450fcec379bdcd5c0
> test: enable back account reordering

- gui/components/community/authenticate_popup.py
- gui/screens/community.py
- gui/screens/community_settings.py
- tests/communities/test_communities.py
- tests/online_identifier/test_online_identifier.py
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1768/
> chore: fixed community admin kiсk member and also changed timeouts 

- gui/components/messaging/clear_chat_history_popup.py
- gui/components/messaging/close_chat_popup.py
- gui/objects_map/messaging_names.py
- gui/objects_map/names.py
- gui/screens/messages.py
- tests/messages/test_messaging_1x1_chat.py
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1784/
also all tests - https://ci.status.im/job/status-desktop/job/e2e/job/manual/1785/
> 1-1 chat: added reply to own message, clear chat and close chat steps

- gui/objects_map/names.py
https://github.com/status-im/status-desktop/pull/14475 depends on this PR so i need to get it merged.
> chore: replace locator for paste sync code button

- gui/main_window.py
- gui/objects_map/names.py
I reworked a bit method of opening community portal, hopefully it helped to stabilise this test
CI run:
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/330/
> chore: edits for communities portal method

- tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py
https://github.com/status-im/status-desktop/issues/14427 should be fixed
ci run https://ci.status.im/job/status-desktop/job/e2e/job/manual/1808/allure/
> chore: enable balance test

- gui/components/back_up_your_seed_phrase_popup.py
- gui/components/wallet/back_up_your_seed_phrase_popup.py
Scroll added to back up seed phrase popup class
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1821/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1822/
> chore: scroll added to back up seed phrase popups

- gui/components/activity_center.py
- gui/components/wallet/send_popup.py
- gui/objects_map/names.py
It still fails because of bug but I fixed steps before that
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1845/
> chore: reworked a bit test of sending nft

- gui/components/community/pinned_messages_popup.py
- gui/objects_map/names.py
- gui/screens/messages.py
- tests/communities/test_communities_pin_and_unpin_messages.py
I reworked how we unpin message, because it was flaky
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1851/
> chore: unpin method reworked

- constants/user.py
- gui/components/changes_detected_popup.py
- gui/objects_map/names.py
- gui/screens/wallet.py
- tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1895/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1896/
> test: custom ordering of assets added

- gui/components/profile_popup.py
- gui/components/settings/send_contact_request_popup.py
- gui/objects_map/names.py
- gui/screens/community.py
- tests/communities/test_communities_add_a_contact_from_member_list.py
- tests/communities/test_communities_adding_contact_from_channel.py
Added test for adding contact from community channel
If you have any suggestions what else to add in this test - let me know
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1930/
> Test: add a contact from community's members list

- tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send.py
- tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send_nft.py
- I split test file on 2 files, it helped to get rid of freezing
- Also returned back `@`
CI run - https://ci.status.im/job/status-desktop/job/e2e/job/manual/1961/allure/#suites/b43d9c6d62f4a41d1125071529e06727
Tests are failing but not freezing. We need to fix them still actually (but after Sale's PR will be merged)
> Splitted send tests

- gui/components/wallet/wallet_account_popups.py
- Added attempts
- Reworked wait_until_appears method for add account popup
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1939/allure/#suites/e5028aa5a5a84c948bb9af2c7ccc9fec/1754ae5a1e64adf6/
> chore: stabilisation rename keypair

- tests/settings/settings_messaging/test_messaging_settings_identity_verification.py
Context: https://github.com/status-im/status-desktop/issues/14954
> test: disable test for identity request as the functionality is going to be hidden

- gui/components/community/invite_contacts.py
- gui/components/context_menu.py
- gui/main_window.py
- gui/objects_map/communities_names.py
- gui/objects_map/names.py
- scripts/utils/browser.py
- tests/communities/test_communities_share_link.py
For now we only verify that there is no 404 error, later I will add verifying some elements of webpage
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1987/
> Share community link test added

- gui/components/online_identifier.py
- gui/components/profile_popup.py
- gui/objects_map/names.py
depends on https://github.com/status-im/status-desktop/pull/15005
- changed locator for the popup https://ci.status.im/job/status-desktop/job/e2e/job/manual/1989/allure/#suites/c779a5502ab37d502705212e4949e67a/a0237964b4428445/
- added proper await method that will wait for the content item to show up
- TODO: add verifications for the buttons to be present (cover https://github.com/status-im/status-desktop/issues/14995).
> chore: improve profile
