status-im/desktop-qa-automation

constants/wallet.py
gui/components/wallet/testnet_mode_popup.py
gui/objects_map/component_names.py
gui/screens/settings.py
tests/test_wallet/test_wallet_settings.py

1. Extended verifications for testnet switching toggle functionality:
> 1. having mainnet enabled, toggle the switch -> click cross button in the corresponding confirmation modal -> that should not enable testnets
> 2. having testnets enabled, toggle the switch -> click cancel button in the corresponding confirmation modal -> that should not enable testnets and should keep the toggle state unchanged (bug was opened in desktop repo https://github.com/status-im/status-desktop/issues/12247 and now it is fixed)
2. Added corresponding scenarios to test rail:
> 1. https://ethstatus.testrail.net/index.php?/cases/view/703621
> 2. https://ethstatus.testrail.net/index.php?/cases/view/703622
3. Fixed broken reference for `is_back_to_wallet_settings_button_present()` (my bad)
4. Added assert messages

tests(@wallet_settings): add negative scenarios

---

constants/wallet.py
gui/elements/qt/object.py
gui/elements/qt/text_edit.py
gui/objects_map/settings_names.py
gui/screens/settings.py
tests/wallet/test_wallet_settings.py

Test that user can open network , see its' details , change the values of RPCs and revert them back
Fixes https://github.com/status-im/desktop-qa-automation/issues/136
**NOTE:** i need to handle checking of red error message and later i will enhance the test with some other verifications for components of the screen
https://ethstatus.testrail.net/index.php?/cases/view/703515

tests(@wallet_settings): edit network

---

constants/syncing.py
gui/objects_map/onboarding_names.py
gui/screens/onboarding.py
tests/test_syncing.py

Added negative scenario for syncing
Changed a bit scenario for syncing during onboarding
https://ethstatus.testrail.net/index.php?/cases/view/703631

Negative scenario: wrong sync code

---

constants/wallet.py
gui/screens/settings.py
tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py
tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py

Fix the test to adjust to new navigation and add verification for toast message
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/420/

fix(@wallet_edit_network): adjust to new designs

---

constants/wallet.py
gui/screens/settings.py
tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py

I wanted to get rid of equal comparison of value in the RPC url field, because i noticed , that the number of `**` symbols differ from build to build (it happens because we use different keys for release , nightly, pr builds). So, to exclude the possible failure when test will compare the exact strings, i replaced the verification with a check that verifies:
- the url starts with the provider url pattern
- the url ends with at least 4 star symbols (normally the api key is longer than 4 symbols).
Having that matching with AND condition allows us to verify:
- the value is reset indeed
- the value is very similar to the one we expect
- the URL will not depend on exact number of stars in the end
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/450/

chore(@edit_network_test): get rid of 1x1 comparison

---

tests/settings/settings_wallet/test_wallet_settings_account_order.py

Account ordering test is fixed and passing now
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/518/

chore(@wallet_settings_tests): enable back account ordering

---

gui/objects_map/settings_names.py
gui/screens/settings_wallet.py
tests/settings/settings_wallet/test_wallet_settings_account_order.py
tests/settings/settings_wallet/test_wallet_settings_edit_status_account.py
tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py

Added verification for Delete button which should not exist for Status account
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/535/

chore(@edit_account_test): add verification for delete button

---

tests/onboarding/test_onboarding_generate_new_keys.py
tests/onboarding/test_onboarding_syncing.py

`test_sync_device_during_onboarding` is enabled now
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/567/

chore(@onboarding_syncing): uncomment sync devices test

---

configs/squish.py
conftest.py
driver/aut.py
driver/context.py
driver/server.py

I found that we Attaching AUT to the default Server port, but the server port changed for each run.
In PR I marked the Squish server as a singleton to have the constant parameters of the Squish server during the test execution.
I added shifting of the squish server port, depending on the build number, to avoid the case when the squish server started on the same port for all parallel jobs.
Test Run, parallel execution:
- https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/556/allure
- https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/555/allure

Fix AttachError because of parallel execution

---

constants/user.py
gui/objects_map/settings_names.py
gui/screens/settings_wallet.py
tests/communities/test_communities.py
tests/communities/test_permissions.py
tests/messages/test_messaging_group_chat.py
tests/onboarding/test_onboarding_import_seed.py
tests/wallet/test_wallet_main_manage_accounts.py

It is important to verify  that when u recover an account, the wallet address of your status account is the one that belongs to your seed phrase
Fixes https://github.com/status-im/desktop-qa-automation/issues/200
https://ci.status.im/job/status-desktop/job/e2e/job/linux-tests/584/

chore(@onboarding_test): add verification for wallet address

---

constants/user.py
gui/components/context_menu.py
gui/objects_map/settings_names.py
gui/screens/settings_wallet.py
tests/wallet/test_wallet_main_manage_accounts.py

- Add verification for status default account is not having delete option in context menu (similar verification is also present in managing accounts from settings). We used to have a bug when delete button was present for status account
- Add verification for importing private account test, so the imported key gets us correct (expected) wallet address
https://ci.status.im/job/status-desktop/job/e2e/job/manual/605/

chore(@wallet_account_tests): make sure status account can't be deleted, as well as correct wallet address is restored for importing account

---

ci/Jenkinsfile

This way we'll see in GitHub PRs that the new job is in progress.

ci: update GitHub check status at job start too

---

gui/screens/settings_wallet.py
tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py

Fix settings tests to handle reworked method of getting toast messages
https://ci.status.im/job/status-desktop/job/e2e/job/manual/643/

chore: settings tests are updated to handle reworked method to get toasts

---

gui/screens/onboarding.py
gui/screens/settings_wallet.py
tests/communities/test_airdrops.py
tests/communities/test_tokens.py
tests/onboarding/test_onboarding_generate_new_keys.py

- hopefully fixes https://github.com/status-im/desktop-qa-automation/issues/215
- also, add attempt param to method which clicks the Next button for onboarding
- comment the new tests for communities, because community creation is still not working properly
https://ci.status.im/job/status-desktop/job/e2e/job/manual/659/

chore: add attempts for clicking network and next buttons

---

gui/screens/onboarding.py
tests/onboarding/test_onboarding_syncing.py

I reviewed the results for our tests in PRs today. I noticed this:
https://ci.status.im/job/status-desktop/job/e2e/job/prs/143/
I made an attempt to fix that by adding additional click for Next button
https://ci.status.im/job/status-desktop/job/e2e/job/manual/700/

chore: add attempts to click on Next button for onboarding

---

constants/user.py
gui/components/signing_phrase_popup.py
tests/wallet_main_screen/test_wallet_main_can_add_account_after_restart.py

Fixes https://github.com/status-im/desktop-qa-automation/issues/238
Test case: https://ethstatus.testrail.net/index.php?/cases/view/704459
CI execution: https://ci.status.im/job/status-desktop/job/e2e/job/manual/724/

test: test_wallet_main_can_add_account_after_restart implemented

---

gui/components/emoji_popup.py
gui/screens/settings.py
tests/wallet_main_screen/test_wallet_main_saved_addresses.py

I made several commits to easier review. I also tested all my commits on poor Linux 03 which was initially causing problems
- EmojiPopUp improved to have a better init, as well as added attempts to select an emoji (there was a problem yesterday, that the test was not able to click / select an emoji , therefore it took 15 minutes for it to eventually fail)
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/771/
- improve selection of Syncing settings option, because I noticed today  the test was not able to click the option (but hovered it)
CI run https://ci.status.im/job/status-desktop/job/e2e/job/manual/772/

Chore: improve emoji popup and syncing settings option selection

---

ci/Jenkinsfile
configs/_local.ci.py
configs/testrail.py
fixtures/testrail.py
requirements.txt

Sending test results in TestRail for nightly regression added:
TESTRAIL_RUN_ID renamed to TESTRAIL_RUN_NAME.
TESTRAIL_RUN_NAME responsible for the report in TestRail:
- if empty - report will be not sent
- if contains value:
- if in TestRail we already have TestRun with the same name, the report will be sent to it
- else TestRun will be created with this name and test cases that were  started in the current session
So for release testing, we can create TestRun with some name and all test cases (or what we need to test for the release), paste the name in the TESTRAIL_RUN_NAME field, and start tests. 
For Nightly regression job:
The scheduled test run will be started with an empty TESTRAIL_RUN_NAME field. In the testrail fixture, I'm using BUILD_URL (Jenkins) to add it to TestRail, and also …

chore: add reporting of nightly results to test rail

---

constants/images_paths.py
constants/user.py
gui/screens/community_settings.py
gui/screens/settings_wallet.py
tests/communities/test_airdrops.py
tests/communities/test_communities.py
tests/communities/test_permissions.py
tests/communities/test_tokens.py
tests/settings/settings_wallet/test_wallet_settings_account_order.py

As was discussed with @anastasiyaig, I replaced images comparison with other verifications and deleted steps with user images comparison (as it's not possible to get source path for such cases) 
The only place I left image comparison is here - https://github.com/status-im/desktop-qa-automation/blob/master/gui/screens/community.py#L44, @StateOf-Vlado can you please do it? (when I tried to get icon's properties color.name and emoji instead of grabbing image - it gave me an error I never understood)

chore: image comparison replaced with other verifications

---

constants/wallet.py
gui/components/wallet/authenticate_popup.py
gui/components/wallet/wallet_account_popups.py
tests/settings/settings_wallet/test_wallet_settings_account_order.py
tests/wallet_main_screen/test_wallet_main_manage_accounts.py
tests/wallet_main_screen/test_wlt_main_add_acc_manage_watched_address.py

Fixes https://github.com/status-im/desktop-qa-automation/issues/56
CI run https://ci.status.im/job/status-desktop/job/e2e/job/manual/788/
- Move the Add watched address to a separate file
- Added a small verification to origin option selected 
- Removed steps with deletion as i plan to cover differently 
- Added a verification for authentication button is not available for adding of watched addresses
**NOTE:** The delete functionality is still being checked in another test

chore: add watched address test is now standalone and matches figma flow

---

constants/aut_options.py
driver/aut.py
fixtures/aut.py
gui/elements/button.py
tests/settings/settings_keycard/test_create_keycard_account_with_new_seed_phrase.py

#260
Test run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/795/
Example:
```
from constants import aut_options
@pytest.mark.parametrize('options', [aut_options.MOCK_KEYCARD])
def test_create_keycard_account_with_new_seed_phrase(main_screen: MainWindow):
pass
```

chore: Mock keycard option added in start AUT

---

tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
tests/wallet_main_screen/test_wallet_main_manage_accounts.py

Added checks for toasts when we delete accounts
Fixes https://github.com/status-im/desktop-qa-automation/issues/285
CI run https://ci.status.im/job/status-desktop/job/e2e/job/manual/848/

chore: managing accounts tests are having the toast verification for deletion

---

ci/Jenkinsfile

A temporary attempt to debug apparent delays possibly caused by running both old and new e2e tests on the same host.
Related to:
* https://github.com/status-im/status-desktop/pull/12697

ci: don't run on agents with desktop-e2e-old label

---

tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py

The newly added test has been recently failed because of loading of balance when adding account. I added waitFor condition that i hope should fix the issue (screenshot with a problem below)
Allure run with a failure https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-297/1/allure/#suites/4516d92a77da5a21d6cc36335b5a380f/1d984f7623d3c560/
Allure report with success https://ci.status.im/job/status-desktop/job/e2e/job/manual/857/allure/#suites/4516d92a77da5a21d6cc36335b5a380f/b4cdaf7cefa7ef1b/

chore: add waiting condition for total balance test so it is not failing on CI

---

ci/Jenkinsfile
configs/testrail.py

#276
We will get the name of the test run from CI, so we don't need to generate a name
Will be resolved here: https://github.com/status-im/desktop-qa-automation/issues/276

chore: Dependence on Jenkins Job name removed in TestRail configs

---

ci/Jenkinsfile

Fixes https://github.com/status-im/status-desktop/issues/12736
I forgot to add `STATUS_RUNTIME_TEST_MODE = '1'` for new tests

chore: add env variable

---

tests/settings/test_settings_back_up_seed.py

We don't have banners when running the app in test mode. I added condition to check the test mode and verify banner when not in test mode, otherwise skip

chore: make the verification of banner conditional in back up seed phrase test

---

ci/Jenkinsfile
driver/aut.py
gui/main_window.py
gui/screens/wallet.py
tests/communities/test_communities.py
tests/onboarding/test_onboarding_import_seed.py
tests/onboarding/test_onboarding_syncing.py
tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py

1. disable test mode, because it leads to unpredictable failures
2. remove keycard references because they are not needed without test mode
3. fixed several tests that were failing
4. increased waiting time for Syncing test as i noticed 10 seconds is not enough sometimes for sync to finish
Changes could be reviewed by commits
CI job: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1069/
Allure report: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1069/allure/

chore: stabilise test

---

constants/group_chat.py
constants/messaging.py
gui/components/toast_message.py
gui/objects_map/component_names.py
gui/objects_map/settings_names.py
gui/screens/settings_messaging.py
gui/screens/settings_wallet.py
tests/messages/test_messaging_group_chat.py
tests/settings/settings_messaging/test_messaging_settings_accept_reject_request.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
tests/settings/settings_wallet/test_wallet_settings_add_account.py
tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py
tests/wallet_main_screen/test_wallet_main_can_add_account_after_restart.py
tests/wallet_main_screen/test_wallet_main_manage_accounts.py
tests/wallet_main_screen/test_wlt_main_add_acc_manage_watched_address.py

I also changed in this task class for toast messages, because I use it in messaging settings tests and  it's not only for wallet anymore
CI report: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1109/
Allure report locally:

test: test_messaging_settings accepting and rejecting request added

---

tests/onboarding/test_onboarding_syncing.py
tests/wallet_main_screen/test_wallet_main_manage_accounts.py
tests/wallet_main_screen/test_wallet_main_saved_addresses.py
tests/wallet_main_screen/test_wlt_main_add_acc_manage_watched_address.py

Syncing test is failing, i logged a task to investigate https://github.com/status-im/desktop-qa-automation/issues/350
Wallet tests are failing because of https://github.com/status-im/status-desktop/issues/12914
The general idea now is to make the run stable and green, no matter of tests content. Once it is stable, i will work on adding skipped tests back. There are also several issues with framework itself, we need to fix them too
Current run was green on CI:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1178/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1178/allure/

Disable wallet tests and syncing test

---

gui/components/settings/sign_out_popup.py
gui/objects_map/settings_names.py
gui/screens/settings.py
tests/settings/test_sign_out_and_quit.py

Added a click to the Sign out button, which was not present
CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1179/

chore: fix sign out test

---

tests/settings/test_settings_sign_out_and_quit.py

Reason to do that: https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/112/allure/
The verification was waiting for 1h

chore: add timeout and assert for the sign out test

---

tests/onboarding/test_password_strength.py

- Update test_password_strength so that all assertions take place in 1 test instead of restarting the app multiple times.
- Add checks for button states
- Remove login tests as these are handled in e2e scenarios
Closes #369

Test: Refactor test_password_strength to speed up indicator checks

---

gui/main_window.py
tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py

Let's try to survive without this `wait_until_appears` because it is unstable
**CI run:** https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-373/1/
**Allure:** https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-373/1/allure/

chore: removed wait until appears from open_wallet method

---

constants/user.py
gui/components/community/welcome_community.py
gui/objects_map/community_names.py
gui/objects_map/component_names.py
gui/objects_map/settings_names.py
gui/screens/community.py
gui/screens/settings_communities.py
tests/communities/test_communities.py
tests/communities/test_communities_channels.py
tests/communities/test_join_community.py

* Fixed join community test (object names changed in the app, also there were some changes in scenarios, so I updated test)
* Got rid of image comparison, in some tests I had to remove it at all (because we don't use screenshots anymore, but it was not possible to replace it with other verifications), in others - just replaced with another verifications (color, emoji etc.)
* Removed skip marks from all communities tests
* Commented one verification (will be enabled after bug is fixed)
* Changed method of getting members and name, because it didn't work anymore in old method
Test run on CI: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1200/allure/

chore: communities tests enabled and fixed, replaced image comparison

---

tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py
tests/settings/test_ens_name_purchase.py

1. I logged https://github.com/status-im/status-desktop/issues/12987 which has some details about cryptocompare
The problem is that we sometimes do not fetch prices and therefore do not show balances on the left panel
2. i also logged https://github.com/status-im/status-desktop/issues/12988 about error with buying ENS

chore: skip balance test and ENS name test because of cryptocompare API limit and coinGecko issue

---

ci/Jenkinsfile
gui/components/delete_popup.py
gui/components/online_identifier.py
gui/components/user_canvas.py
gui/components/wallet/popup_delete_account_from_settings.py
gui/main_window.py
gui/objects_map/component_names.py
gui/screens/community.py
gui/screens/community_settings.py
gui/screens/settings.py
gui/screens/settings_communities.py
gui/screens/settings_wallet.py
tests/communities/test_communities_channels.py
tests/communities/test_join_community.py
tests/messages/test_messaging_group_chat.py
tests/onboarding/test_onboarding_generate_new_keys.py
tests/onboarding/test_onboarding_import_seed.py
tests/onboarding/test_onboarding_negative_scenarios.py
tests/onboarding/test_onboarding_syncing.py
tests/online_identifier/test_online_identifier.py
tests/settings/settings_messaging/test_messaging_settings_accept_request.py
tests/settings/settings_messaging/test_messaging_settings_identity_verification.py
tests/settings/settings_messaging/test_messaging_settings_reject_request.py
tests/settings/settings_profile/test_settings_profile_change_password.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_edit_status_account.py
tests/wallet_main_screen/test_send.py

https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-378/23/allure/
I can reproduce the UI issues on my Linux machine as well
In this branch i tried to solve them. I really hope they all will be gone after upgrade to QT 5.15.10 on Linux so all these tweaks wont be necessary
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1205/allure/#suites/804b25da7c0d1c4c7f8a050c6a89e043/e047a6e57785f1f0/
Overall the test mode **is NOT yet enabled**. I am waiting for https://github.com/status-im/status-desktop/pull/9232 to test it there
- in `test_edit_community` added time.sleep when we load from for community overview and the same small time sleep when we start building the list of communities on settings screen
- in `test_community_category` i added attempts to click …

Chore/test mode: stabilise tests to allow them pass in STATUS_RUNTIME_TEST_MODE = True

---

gui/components/change_password_popup.py
gui/screens/onboarding.py
pytest.ini
tests/communities/test_airdrops.py
tests/communities/test_communities.py
tests/communities/test_communities_categories.py
tests/communities/test_communities_channels.py
tests/communities/test_permissions.py
tests/communities/test_tokens.py
tests/onboarding/test_onboarding_generate_new_keys.py
tests/online_identifier/__init__.py
tests/online_identifier/test_online_identifier.py
tests/settings/settings_profile/test_settings_profile_change_password.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
tests/settings/test_settings_back_up_seed.py
tests/settings/test_settings_sign_out_and_quit.py
tests/wallet_main_screen/test_context_menu_manage_watched_address.py

1. Selected a few tests to run by `critical` mark in PRs (`pytest -m critical`)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1213/
If this selection is good, i will make the corresponding change in status-desktop repo, so in desktop PRs , we will run these 8 tests for now
2. Improved the change password test a bit, because it hangs for 15 minutes (https://ci.status.im/job/status-desktop/job/e2e/job/manual/1215/allure/#suites/67eac0031245ff48294e4d11dc8f3332/b19140088c319653/)

chore: select tests to run against PRs

---

gui/components/change_password_popup.py

There is a problem with is_visible method now, it is not raising any assertions in case it did not find any object, therefore i suspect it as a potential endless loop (always returns True it seems). I will try to fix that, however it is being used across all the framework so it takes time.
The main idea here is to get rid of endless loop and 15 minutes if waiting for nothing in this certain test

chore: replace waitFor with waitForObjectExists

---

gui/screens/community_portal.py
tests/onboarding/test_onboarding_syncing.py

Community categories tests got stuck for 15 minutes because of `wait_until_appears` method
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/134/allure/ (nightly run)
CI run with critical mark https://ci.status.im/job/status-desktop/job/e2e/job/manual/1236/
CI run with all communities suite
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1237/console

chore: replace is_visible

---

README.md
pytest.ini
requirements.txt
tests/settings/settings_profile/test_settings_profile_change_password.py

Motivation: do not spent extra 15 minutes on nothing
Fixes https://github.com/status-im/desktop-qa-automation/issues/413
https://pypi.org/project/pytest-timeout/
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/137/allure/
In case of test hangs, it will be timed out within given timeout value. Right now i set this mark for only 1 test
`@pytest.mark.timeout(timeout=180, method="thread")`, timeout is set for 3 minutes (could be reduced later, lets see)
I did not set any default timeout across the framework yet. it could be done later in pytest.ini file

Introduce pytest timeout mark

---

tests/messages/test_messaging_group_chat.py

Group chat test was stuck in last nightly and its duration was 36m 53s
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/139/allure/#testresult/5f9296a7ddfa5053
I am setting this test to force timeout after 240 seconds (4 minutes). Normally this test passes within ~3 minutes, so i am adding extra minute just in case. Anyhow. 36 minutes is crazy

chore: add timeout for group chat

---

constants/community_settings.py
constants/user.py
gui/objects_map/community_names.py
gui/screens/community_settings.py
tests/communities/test_permissions.py

**Fixes** https://github.com/status-im/desktop-qa-automation/issues/421
**Depends** on https://github.com/status-im/status-desktop/pull/13110
1. add randomisation for community name and description when creating
2. added toast message verification step
3. added methods to verify tags specifically
4. added verification for `in_channel`, `in_community`
**Todo:** 
- remove parametrisation and use test sets inside the test (to reduce test time)
- to create a test for critical suite (perhaps break this one into several, 1 test will be marked as critical)
**ci run:** https://ci.status.im/job/status-desktop/job/e2e/job/manual/1249/
**allure:** https://ci.status.im/job/status-desktop/job/e2e/job/manual/1249/allure/#suites/a9b9ce4ef70730fb5814a5009e98b445

chore: fix test for creating permissions

---

tests/settings/settings_profile/test_settings_profile_change_password.py

Remove `@pytest.critical` mark from `test_settings_profile_change_password.py`. The test is timing out very often now (addressed in https://github.com/status-im/status-desktop/issues/13013) which indicates the run against PRs in desktop repository as failures. I want to make this selection of tests (by `critical` mark) to be always green, so we finally switch off old tests and start relying on new ones
This test will be still executed in nightly runs

chore: remove change password test from critical suite

---

tests/settings/test_settings_sign_out_and_quit.py

This is an experimental thing:
1. removed `pytest.mark.case` marker in 1 test. I cant find any documentation about this marker in official docs or `pytest.ini`
2. TEMP added a second link for a test case reference (`@allure.testcase`). Want to test how it would post the report from allure to test rail (and this is now possible only with nightly job). My expectation (and biggest hope) is that this move would allow us to map 1 automated script with multiple test cases in test rail

chore: add multiple references for tests

---

constants/onboarding.py
constants/wallet.py
gui/components/wallet/wallet_account_popups.py
gui/objects_map/onboarding_names.py
gui/screens/onboarding.py
gui/screens/settings_wallet.py
tests/wallet_main_screen/test_plus_button_add_watched_address.py

Onboarding CI run: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1261/allure/#suites/8c8bad42b349ab7d648f7a8503fdb961/3ac4673cfec5e7d2/
Wallet CI run:https://ci.status.im/job/status-desktop/job/e2e/job/manual/1263/allure/#suites/96c8fa12a723416450fcec379bdcd5c0
- added verify_account_popup_present() function
- added verify_profile_view_present() function
- added verify_emojihash_view_present()
Mostly done as an attempt to fix flaky navigation in new keys test. (see https://ci.status.im/job/status-desktop/job/e2e/job/prs/1136/allure/#suites/c48b221cdcfecf89e1eb75d0b8e79672/f41783642f763391/)
So the test clicks Next button twice and then thinks he is already on next screen when it is not. So i added a verification for Profile and Emoji screens that when we returning these …

chore: replace methods of waiting views with methods of checking elements on these views

---

tests/settings/test_settings_sign_out_and_quit.py

I tested it here https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/161/
Test report is here - https://ethstatus.testrail.net/index.php?/runs/view/14414&group_by=cases:section_id&group_order=asc 
So it was successfully reported to 2 test cases. Let's see how it works in nightly

chore: reporting test to 2 different test cases in Testrail

---

gui/objects_map/wallet_names.py
gui/screens/wallet.py
tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py
tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py
tests/wallet_main_screen/test_saved_addresses.py

- Saved addresses tests fixed
- Edit networks test skipped for now (will work on it tomorrow, it usually passes on Mac, so I tried many times and only 1 time failed, I even didn't manage to realise what is the issue)
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1267/
Allure report locally:

chore: fixes for saved addresses tests

---

tests/communities/test_join_community.py
tests/messages/test_messaging_group_chat.py
tests/settings/settings_messaging/test_messaging_settings_accept_request.py
tests/settings/settings_messaging/test_messaging_settings_identity_verification.py
tests/settings/settings_messaging/test_messaging_settings_reject_request.py

As contact requests works fine now, I'm enabling tests
CI runs:
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/181/
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/182/

chore: enabling tests with contact requests

---

tests/communities/test_communities_channels.py
tests/communities/test_join_community.py
tests/messages/test_messaging_group_chat.py

- Increased timeout in group chat test
- Changed a way we get chat key
- Enabled tests after bug fix for community links
- Edit channel didn't work yesterday (tried to find a reason, but no success), but today after fix it works just great!
CI runs for communities and messaging : 
- https://ci.status.im/job/status-desktop/job/e2e/job/manual/1300/

chore: fix for failed tests and enabling some tests after bug fix

---

gui/components/wallet/send_popup.py
tests/communities/test_communities_permissions.py
tests/wallet_main_screen/wallet: footer actions/test_send.py

- Skipped test_send and added more verifications so test will not take forever
- Skipped test_adding_permissions
Allure report - to show that verifications work - now test fails when there is no asset available

chore: skipped tests and added more asserts

---

constants/settings.py
gui/components/change_password_popup.py
gui/objects_map/component_names.py
gui/objects_map/settings_names.py
gui/screens/settings.py
gui/screens/settings_password.py
gui/screens/settings_profile.py
tests/settings/settings_password/test_settings_password_change_password.py

Fixes #500 
CI run: https://ci.status.im/job/status-desktop/job/qa-automation/job/prs/job/PR-503/7/allure

chore: fix failing tests and adjust change password test to new designs

---

gui/components/profile_popup.py
gui/objects_map/component_names.py
tests/communities/test_communities_pin_and_unpin_messages.py
tests/communities/test_join_community.py
tests/onboarding/test_onboarding_generate_new_keys.py
tests/settings/settings_messaging/test_messaging_settings_accept_request.py
tests/settings/settings_messaging/test_messaging_settings_identity_verification.py
tests/settings/settings_messaging/test_messaging_settings_reject_request.py

- Fixed locator for chat key
- Fixed wrong assert in pin and unpin message
- Fixed method we get chat key in join community
CI runs:
- https://ci.status.im/job/status-desktop/job/e2e/job/manual/1374/
- https://ci.status.im/job/status-desktop/job/e2e/job/manual/1373/
- https://ci.status.im/job/status-desktop/job/e2e/job/manual/1372/

chore: fixes for fails from nightly run

---

gui/components/change_password_popup.py
tests/settings/settings_password/test_settings_password_change_password.py

I noticed that the problem with slow rehasing is still there https://github.com/status-im/status-desktop/issues/13013
And it fails the critical path now in some PRs

chore: mark change password test as xfail again

---

ci/Jenkinsfile
ext/allure_files/categories.json
ext/allure_files/environment.properties

- Added categories for errors in Allure report. For now I defined these categories, @anastasiyaig if you have more ideas about popular errors, let me know I will add more 
- Also added environment section for our Allure report. I think in this section we can add useful info for those who doesn't really know a lot about our attests. It may help to understand the issue. So, the same here, @anastasiyaig  if you have ideas what else to put here - let me know
Example of CI run with changes:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1365/allure/
Allure report will look smth like this:

chore: categories and environment section added to allure report

---

gui/components/community/create_community_popups.py
gui/components/picture_edit_popup.py
gui/objects_map/names.py
gui/screens/community_settings.py
gui/screens/onboarding.py
tests/onboarding/test_onboarding_generate_new_keys.py
tests/onboarding/test_onboarding_import_seed.py
tests/settings/settings_password/test_settings_password_change_password.py
tests/settings/settings_profile/test_settings_profile_edit.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_add_account_after_restart.py

Onboarding tests on linux 03: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1418/allure/
Critical path run on linux 03: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1423/allure/
Full run on Linux 03: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1425/allure/#suites/c48b221cdcfecf89e1eb75d0b8e79672/4859437cf715a99b/

chore: replace file upload dialog usage

---

constants/community_settings.py
gui/components/changes_detected_popup.py
gui/components/delete_popup.py
gui/objects_map/names.py
gui/screens/community_settings.py
tests/communities/test_communities_permissions.py
tests/settings/settings_profile/test_settings_profile_edit.py

Permissions test has been updated. I added 3 separate test cases (creating, editing and deleting) and we will just report to all 3. Added critical mark to 2 of parameters.
I also tried to fix Attribute error by refactoring methods where the error occur. Let's see if it helped. 
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1429/

test: updated permission test with editing and deleting

---

tests/communities/test_communities_channels.py

Need to address https://github.com/status-im/desktop-qa-automation/issues/535 first , then enable test back

chore: remove channel test from critical path for now

---

tests/onboarding/test_onboarding_import_seed.py
tests/settings/settings_password/test_settings_password_change_password.py

- removed the flaky mark from change password test
- increased timeout for 30 seconds just now (i communicated that to be enough)
We need this test to show actual result , because we missed https://github.com/status-im/status-desktop/issues/13748 because of this
~**TODO:** enable this test back to critical path when bug is fixed. This test will now fail in master~

chore: remove flaky mark from change password test

---

fixtures/testrail.py

I added checking response status code and skipping testrail report in case it's not 200.
This is done because several times we faced the issue that Testrail is not reachable and all tests were red because of this

chore: skipping testrail report if we get testrail error

---

gui/components/settings/build_your_showcase_popup.py
gui/components/wallet/testnet_mode_popup.py
gui/objects_map/names.py
gui/screens/community.py
gui/screens/settings_profile.py
tests/communities/test_communities_channels.py
tests/onboarding/test_onboarding_negative_scenarios.py
tests/onboarding/test_password_strength.py

- Fixed dots format in password strength test 
- Added class build showcase popup and closing it if needed
- Removed selected verification for channel test
- Saved address test will be fixed in a separate task, toast messages - also, we also need to investigate application context thing (also separate ticket), there is also a bug - reported
CI - https://ci.status.im/job/status-desktop/job/e2e/job/manual/1510/allure/ 
https://ci.status.im/job/status-desktop/job/systems/job/linux/job/x86_64/job/tests-e2e-new/227/allure/#suites/8c8bad42b349ab7d648f7a8503fdb961/b058e9d9f4485be1/ - the latest nightly

chore: fix nightly fails

---

driver/aut.py

trying to grab more logs in aut.py file to culprit the issue with connection refused error
run 1: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1493/console
run 2: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1497/console

Add more logs to the aut instance

---

ci/Jenkinsfile
driver/aut.py
gui/components/change_password_popup.py
pytest.ini
requirements.txt
tests/onboarding/test_onboarding_generate_new_keys.py

Partially addresses https://github.com/status-im/desktop-qa-automation/issues/558
- replace `-d` with correct `-datadir`
- add rerun attempt for failed tests
- some small changes on the go

Implement reruns functionality and fix data directory parameter

---

gui/objects_map/names.py
gui/screens/settings.py

Changed a bit how we refer to the left panel on settings page, i feel we used the wrong left panel object before. 
Also, changed a reference to the settings option template
Full run (rebased) https://ci.status.im/job/status-desktop/job/e2e/job/manual/1582/console

Chore improve locator

---

gui/components/changes_detected_popup.py
gui/screens/settings_profile.py
tests/online_identifier/test_online_identifier.py
tests/settings/settings_profile/test_settings_profile_edit.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_edit_status_account.py

Fixes #579 
Tests for edit profile form should now catch the fact if save button was clicked and closed
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1614/allure/#suites/c779a5502ab37d502705212e4949e67a/a4315dd8067931d2/
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1615/allure/#suites/bafa0acf6e88ebdd47b4ecdbd9040f15/facd4f3b61539239/
Full run is still good https://ci.status.im/job/status-desktop/job/e2e/job/manual/1618/allure/

chore: improve validation for edit profile form

---

.gitignore
configs/testpath.py
conftest.py
driver/aut.py
fixtures/aut.py
requirements.txt

- do not remove application log files after local test runs (it will help investigate issues if any)
- improve folders naming: use uuid for app directory name, and improve test run name to make it more readable
- get rid of 'temp' folder and inner 'status' folder
Result: we have now **local run results** folder (former TEMP) and inside of it there are different run folders which contain application data folders of the applications started. If test is failing, then additional folder is generated with suite name and screenshots. Improved screenshots generation so we don't create unnecessary one now
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1598/allure/

chore: do not remove log files for local runs and improve the folder namings

---

gui/components/toast_message.py
gui/main_window.py
gui/screens/settings_wallet.py
tests/communities/test_communities_permissions.py
tests/settings/settings_messaging/test_messaging_settings_accept_request.py
tests/settings/settings_messaging/test_messaging_settings_identity_verification.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
tests/settings/settings_wallet/test_wallet_settings_add_account.py
tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py
tests/settings/settings_wallet/test_wallet_settings_networks_testnet_mode.py
tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_add_account_after_restart.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_add_watched_address.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_manage_account_added_for_new_generated_seed.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_manage_account_from_private_key.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_manage_account_from_seed_phrase.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_manage_generated_account.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_manage_generated_account_custom_derivation_path.py
tests/wallet_main_screen/wallet: right click out of account area/test_right_click_manage_watched_address.py
tests/wallet_main_screen/wallet: saved addresses/test_saved_addresses.py

- Reworked methods of getting toast messages
- Replaced in steps to wait_for_notification method
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1628/allure/

chore: reworked toast message verification in tests

---

tests/online_identifier/test_online_identifier.py
tests/settings/settings_profile/test_settings_profile_edit.py

Enable back tests that were disabled because of https://github.com/status-im/status-desktop/issues/13799
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1634/allure/#suites/bafa0acf6e88ebdd47b4ecdbd9040f15/e5765c4125cd8e33/
I logged a task to re-work this "partial" click that happens from time to time https://github.com/status-im/desktop-qa-automation/issues/585
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1635/allure/#suites/dc13814b122239ff980c4e5033f4b805

chore: enable tests for editing profile

---

gui/components/onboarding/before_started_popup.py
gui/components/wallet/add_saved_address_popup.py
gui/elements/button.py
gui/elements/check_box.py
gui/elements/object.py
gui/main_window.py
gui/screens/community.py
gui/screens/messages.py
gui/screens/wallet.py

Closes #585 
CI run_1 full scope: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1660/allure/
CI run_2 full scope: https://ci.status.im/job/status-desktop/job/e2e/job/manual/1662/console
Removed duplicated native click
Aligned click with left and right buttons to both using Qt buttons
Renamed a method of right clicking to be named like that
Removed unnecessary (?) extra click method in Button class
```
x or int(self.object.width * 0.1),
y or int(self.object.height * 0.1),
```
this is done to avoid clicking in the middle of the object, also these params must be int otherwise they are not accepted by mouseClick and then it is defaulted to click to the center of the object. We dont want to have that just because for some elements (like checkboxes) clicking in the center may lead …

chore: remove duplicated click

---

fixtures/aut.py

I am brining back logs removal in application logs function just because having so many files right now in allure report is annoying.
This will again leave us with logs folder empty for local runs. I think, this function should be revisited again later, desired bahvior:
- we have logs in logs folder when running tests locally
- we also have logs (1 file per test) attached in allure report
Will work on that later

chore: bring back logs clean up

---

tests/communities/test_communities_categories.py

Test skipped because now I cannot update user data (because of bug https://github.com/status-im/status-desktop/issues/14011). So I created a separate task and will update user data and enable test back later

chore: skip test_member_role_cannot_add_edit_or_delete_category

---

pytest.ini
tests/communities/test_communities_categories.py
tests/settings/settings_messaging/test_messaging_settings_reject_request.py
tests/settings/settings_password/__init__.py
tests/settings/settings_profile/test_settings_profile_edit.py
tests/settings/settings_wallet/test_wallet_settings_account_order.py
tests/settings/settings_wallet/test_wallet_settings_acct_interactions_delete_account.py
tests/settings/settings_wallet/test_wallet_settings_add_account.py
tests/settings/settings_wallet/test_wallet_settings_networks_edit_network.py
tests/settings/settings_wallet/test_wallet_settings_saved_addresses_add.py
tests/settings/test_ens_name_purchase.py
tests/settings/test_settings_back_up_seed.py

Enabled back `test_settings_profile_edit`, changed assert messages, added missing marks where noticed, removed unused imports

chore: add missing marks and enabled profile edit test

---

gui/objects_map/names.py
gui/screens/wallet.py
tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py
tests/wallet_main_screen/wallet: assets_sorting/test_wallet_sorting.py

Added test for assets sorting
Assets sorting: https://ethstatus.testrail.net/index.php?/cases/view/727223
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1686/allure/#suites/514ff75bb3f68febb5d77eaf0f4cb4fc/6eeace095ee43dee/

test: assets sorting test added

---

driver/aut.py
driver/context.py

Removed unnecessary code that was added before. The code is not really working and the real reason for context being invalid (not found , none) is that the application crashes from time to time and we dont really handle that with Squish logic. Current workaround is if test failed - retry it 1 time. So no inner loops are needed and they are useless anyway

chore: clean up in context.py

---

tests/onboarding/test_onboarding_generate_new_keys.py

Noticed that there is an incorrect comparison of object type with a string

chore: fix data type in public key assertion

---

gui/components/wallet/send_popup.py
gui/objects_map/names.py
gui/screens/settings_wallet.py
tests/communities/test_communities_categories.py
tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py
tests/settings/test_ens_name_purchase.py
tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send.py

Fixes https://github.com/status-im/desktop-qa-automation/issues/26
Depends on https://github.com/status-im/status-desktop/pull/14306
- Enable back ens purchase test
- Enable back total balance test
- Enable back community categories test
- Fix and enable back send ether test
I ran the test on the build with the new locator (it is not from nightly job )
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1744/allure/#suites/a549ff0f1f607186f4dd560a40d3c78d/6cf5ff14bb7dcb57/

test: fix send asset test and enable other tests

---

constants/community_settings.py
gui/components/community/kick_member_popup.py
gui/main_window.py
gui/objects_map/communities_names.py
gui/objects_map/messaging_names.py
gui/objects_map/names.py
gui/screens/community_settings.py
gui/screens/messages.py
tests/communities/test_communities.py

Community admin can delete member's message and kick a member test automated
CI run (all tests): 
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1748/allure/

test: admin can kick a member and delete message

---

ci/Jenkinsfile

Desktop QA tests also use Pytest packages and their versions are different, so we can't install them globally, it needs to be done per build using `WORKSPACE_TMP` as destination.
Otherwise you get this due to a race condition:
```
> a ci-slave-linux,ci-slave-release -o -a 'sudo -u jenkins pip list --user 2>/dev/null | grep "^pytest "' | sort
linux-01.he-eu-hel1.ci.release | CHANGED | rc=0 | (stdout) pytest  7.4.0
linux-02.he-eu-hel1.ci.release | CHANGED | rc=0 | (stdout) pytest  7.4.0
linux-01.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) pytest    7.2.1
linux-02.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) pytest    7.4.0
linux-03.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) pytest    7.4.0
linux-04.he-eu-hel1.ci.devel | CHANGED | rc=0 | (stdout) pytest    7.4.0 …
```

ci: use virtualenv to avoid race conditions

---

gui/objects_map/names.py
gui/screens/onboarding.py
tests/onboarding/test_onboarding_syncing.py

PR for release: https://github.com/status-im/status-desktop/pull/14485
I accidentally used incorrect object name (i renamed in main repo after review and forgot to rename here)
Fixed syncing test to stop if failing in release branch all the time
Tests were ran manually against the build with new object name (no nightly yet , it is building now)
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1789/allure/

Fix syncing test

---

tests/settings/test_ens_name_purchase.py
tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py
tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send.py

Right now more people are interested in nightly runs, so I think we need to stop disabling tests because of known issues in the product, to indicate clearly what is not working currently. 
This is not related to flaky tests that has to be stabilised before being enabled

chore: enable failing tests to reflect the current picture

---

gui/screens/community.py
gui/screens/settings_messaging.py
tests/communities/test_communities.py
tests/communities/test_communities_channels.py
tests/settings/test_settings_back_up_seed.py

- remove colors validations. Fixes https://github.com/status-im/desktop-qa-automation/issues/535. NOTE: we need to address https://github.com/status-im/desktop-qa-automation/issues/658 and then bring the test back to critical path
- raise lookup error if contacts list is empty
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1826/allure/#suites/a9b9ce4ef70730fb5814a5009e98b445

chore: remove colors verification from channels test

---

gui/main_window.py
tests/onboarding/test_onboarding_syncing.py
tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send.py

- Fixed cancel setup syncing test because of changes in product (https://github.com/status-im/status-desktop/pull/14633)
- Added one more attempt for opening wallet (for some reason it keep not opening sometimes)
- Set timeout for send tests
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1909/allure/#suites/a549ff0f1f607186f4dd560a40d3c78d/9f10929004983281/ (fail expected - there is a bug)

Chore/fix nightly 15.05

---

constants/links.py
constants/messaging.py
gui/components/messaging/link_preview_options_popup.py
gui/objects_map/messaging_names.py
gui/objects_map/names.py
gui/screens/messages.py
gui/screens/settings_messaging.py
tests/messages/test_messaging_link_previews.py

Added tests for link previews. Test cases:
https://ethstatus.testrail.net/index.php?/cases/view/704596
https://ethstatus.testrail.net/index.php?/cases/view/704578
https://ethstatus.testrail.net/index.php?/cases/view/704579
Allure report:
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1924/

test: link preview tests added

---

constants/onboarding.py
gui/components/onboarding/keys_already_exist_popup.py
gui/objects_map/names.py
gui/screens/onboarding.py
tests/onboarding/test_onboarding_import_seed.py

I added re-importing seed phrase and verifying keys already exist popup to existing test. 
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1937/

test: re-importing seed phrase added to existing test

---

gui/main_window.py
gui/objects_map/messaging_names.py
tests/communities/test_communities_mint_owner_token.py

Depends on https://github.com/status-im/status-desktop/pull/14953
Motivation:
CI run of a test itself:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1945/
CI full run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1948/parameters/ 
**NOTE:** the send wallet test is getting stuck (same in nightly for several weeks already). Thats not an issue with current PR

Add transaction mark and stabilise 1x1 chat test

---

tests/settings/settings_wallet/test_wallet_settings_watched_addr_include_in_total_balance.py
tests/settings/test_ens_name_purchase.py
tests/wallet_main_screen/wallet: assets tab/test_wallet_assets_sorting.py
tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send.py
tests/wallet_main_screen/wallet: footer actions/test_footer_actions_send_nft.py

As was discussed, we are disabling tests dependant on rates limits issues. Will get back to them later
TODO: 
- monitor linked tickets https://github.com/status-im/status-desktop/issues/14509, https://github.com/status-im/status-desktop/issues/14862
- implement https://github.com/status-im/desktop-qa-automation/issues/385 and try to use it with transactions (tests that are sending something or verifying chart / balance changes)

Skipped tests dependent on issues with rates limits

---

constants/wallet.py
gui/components/wallet/wallet_account_popups.py
gui/objects_map/names.py
tests/wallet_main_screen/wallet: plus button/test_plus_button_manage_account_from_seed_phrase.py

Added test for re-importing seed phrase in wallet
CI run:
https://ci.status.im/job/status-desktop/job/e2e/job/manual/1943/allure/#suites/da6cc84cf3fb97eff5906c899e088133/99d73282a3eb1e43/

 Re-importing seed phrase in wallet
